### PR TITLE
Hw01 task05

### PR DESCRIPTION
**Pull request by julwein**

### CODE REVIEW

**Review by Cjkjvfnby — CHANGES_REQUESTED** [review]
Do you see something strange in this PR?

What other cases can we test here?

**Comment by julwein** [comment]
> Do you see something strange in this PR?

Sorry, not really, what is it?

**Comment by Cjkjvfnby** [comment]
> Sorry, not really, what is it?

image

**Review by Cjkjvfnby — CHANGES_REQUESTED** [review]
Lets add more test cases.

**Comment by julwein** [comment]
Please give a clue what other cases may need considering?

**Comment by Cjkjvfnby** [comment]
> Please give a clue what other cases may need considering?

Which numbers are present in the sample and not in your tests?

**Review by Cjkjvfnby — APPROVED** [review]

**Pull request merged**
